### ISSUE TITLE
Getting 404 

### ISSUE THREAD

**Issue by rod-farvas-mustache** [emesday/prefixed-superset#4]
Not sure what I'm doing wrong.  Containers come up fine using docker-compose using SUPERSET_CONTEXT_PATH=mysuperset docker-compose up -d

When typing in http://crm.xxxxx.com/mysuperset my browser just gives me a 404 and shows this in my url http://crm.xxxxx.com/superset/welcome/

Nginx container log 
192.168.1.49 - - [19/Jan/2023:20:33:15 +0000] "GET /mysuperset HTTP/1.1" 301 180 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
192.168.1.49 - - [19/Jan/2023:20:33:15 +0000] "GET /mysuperset/ HTTP/1.1" 302 261 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
2023/01/19 20:33:15 [error] 9#9: *1 "/etc/nginx/html/superset/welcome/index.html" is not found (2: No such file or directory), client: 192.168.1.49, server: , request: "GET /superset/welcome/ HTTP/1.1", host: "crm.xxxxx.com"
192.168.1.49 - - [19/Jan/2023:20:33:15 +0000] "GET /superset/welcome/ HTTP/1.1" 404 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
192.168.1.49 - - [19/Jan/2023:20:33:29 +0000] "GET /superset/welcome/ HTTP/1.1" 404 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "-"
2023/01/19 20:33:29 [error] 9#9: *1 "/etc/nginx/html/superset/welcome/index.html" is not found (2: No such file or directory), client: 192.168.1.49, server: , request: "GET /superset/welcome/ HTTP/1.1", host: "crm.xxxxx.com"

superset container log
172.25.0.3 - - [19/Jan/2023:20:33:15 +0000] "GET / HTTP/1.0" 302 223 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

**Comment by blzsaa** [comment]
try http://crm.xxxxx.com/mysuperset/superset/welcome/, that worked for me

**Comment by rod-farvas-mustache** [comment]
Sorry for the late response as I haven't been able to work on this.  Even with the new link I still couldn't pull up the page until I added this to the superset.conf.template

 location / { 
            proxy_pass http://superset-nginx;
        }


Thanks for the help!
